//besmellah

#pragma once

#include "show.h"

void init();
void Define_global_size_variables();

void init () {
	SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER);
	WINDOW = SDL_CreateWindow("State.io", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, 1240, 640, SDL_WINDOW_OPENGL);
	RENDERER = SDL_CreateRenderer(WINDOW, -1, SDL_RENDERER_ACCELERATED);
	SDL_SetRenderDrawColor(RENDERER, 0xee, 0xdd, 0xcc, 0xff);
	SDL_RenderClear(RENDERER);
//	Add SDL_WINDOW_RESIZABLE to flags.

	SDL_GL_GetDrawableSize(WINDOW, &SCREEN_WIDTH, &SCREEN_HEIGHT);
	WINDOW_PADDING_UP = SCREEN_HEIGHT / 5;
	WINDOW_PADDING_RIGHT = SCREEN_WIDTH / 15;
	WINDOW_PADDING_DOWN = SCREEN_HEIGHT / 10;
	WINDOW_PADDING_LEFT = SCREEN_WIDTH / 15;
}

void Define_global_size_variables() {
	WIDTH = SCREEN_WIDTH - WINDOW_PADDING_RIGHT - WINDOW_PADDING_LEFT;
	HEIGHT = SCREEN_HEIGHT - WINDOW_PADDING_UP - WINDOW_PADDING_DOWN;
	
	CELL_WIDTH = WIDTH / GRID_WIDTH;
	CELL_HEIGHT = HEIGHT / GRID_HEIGHT;

	WIDTH = GRID_WIDTH * CELL_WIDTH;
	HEIGHT = GRID_HEIGHT * CELL_HEIGHT;

	int mn = min(CELL_WIDTH, CELL_HEIGHT);

	CASTLE_SIZE = mn * 4.0 / 5.0;
	
	for (int i = 0; i < GRID_WIDTH; i++) {
		for (int j = 0; j < GRID_HEIGHT; j++) {
			GRID[i][j].x1 = WINDOW_PADDING_RIGHT + i * CELL_WIDTH;
			GRID[i][j].y1 = WINDOW_PADDING_UP + j * CELL_HEIGHT;
			GRID[i][j].x2 = GRID[i][j].x1 + CELL_WIDTH;
			GRID[i][j].y2 = GRID[i][j].y1 + CELL_HEIGHT;
		}
	}
}
